[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_git_versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "tag_update_helper"
dynamic = ["version"]
authors = [
    { name="NTS Cloud Openstack", email="iaas.openstack@bell.ca" },
]
description = "package to update tags inside Openstack NFVI R1 projects"
requires-python = ">=3.7"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]
dependencies = [
    'GitPython',
    'requests',
    'python-gitlab>=3.10'
]

[project.scripts]
tag_updater = "tag_version_updater.tag_updater:main"
send_slack_report = "tag_version_updater.send_slack_report:main"

[tool.setuptools.packages]
find = {}

[tool.setuptools-git-versioning]
enabled = true

[distutils]
index-servers = [
    "gitlab"]

[gitlab]
repository = "https://gitlab.bell.ca/api/v4/projects/24131/packages/pypi"
username = "gitlab-ci-token"
password = "test"